#!/usr/bin/env bash
set -Eeuo pipefail

# index.sh - Main menu for shell-setup scripts
# Provides a unified entry point to select and run setup scripts

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; DIM='\033[2m'; NC='\033[0m'

# ── Load .env API keys ──────────────────────────────────
load_env() {
  local env_file=""
  local search_paths=(
    "$SCRIPT_DIR/.env"
    "$HOME/.env"
    "/storage/emulated/0/vault/03-personal/04-secrets/.env"
    "/storage/emulated/0/vault/.env"
  )
  for p in "${search_paths[@]}"; do
    if [[ -f "$p" ]]; then
      env_file="$p"
      break
    fi
  done

  if [[ -z "$env_file" ]]; then
    return 0
  fi

  local count=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// /}" ]] && continue
    if [[ "$line" =~ ^[[:space:]]*([A-Za-z_][A-Za-z0-9_]*)=(.+)$ ]]; then
      local key="${BASH_REMATCH[1]}"
      local val="${BASH_REMATCH[2]}"
      export "$key=$val"
      ((++count))
    fi
  done < "$env_file"

  printf "${GREEN}✓ Loaded %d env vars from %s${NC}\n" "$count" "$env_file"
}

load_env

# ── askall configuration ─────────────────────────────────

ASKALL_CONFIG_DIR="$HOME/.config/askall"
ASKALL_CONFIG="$ASKALL_CONFIG_DIR/config.env"

# Provider catalog: provider_id → env_var
# Inspired by hive-research registry pattern
declare -A PROVIDER_ENV=(
  [openai]="OPENAI_API_KEY"
  [anthropic]="ANTHROPIC_API_KEY"
  [google]="GOOGLE_API_KEY"
  [openrouter]="OPENROUTER_API_KEY"
  [groq]="GROQ_API_KEY"
  [deepseek]="DEEPSEEK_API_KEY"
  [cerebras]="CEREBRAS_API_KEY"
  [sambanova]="SAMBANOVA_API_KEY"
  [together]="TOGETHER_API_KEY"
  [cohere]="COHERE_API_KEY"
  [siliconflow]="SILICONFLOW_API_KEY"
  [hyperbolic]="HYPERBOLIC_API_KEY"
  [deepinfra]="DEEPINFRA_API_KEY"
  [upstage]="UPSTAGE_API_KEY"
  [venice]="VENICE_API_KEY"
)

# Known models per CLI tool
CLAUDE_MODELS=(
  "claude-sonnet-4-20250514"
  "claude-opus-4-20250514"
  "claude-haiku-4-5-20251001"
  "claude-3-5-sonnet-20241022"
)
GEMINI_MODELS=(
  "gemini-2.5-flash"
  "gemini-2.5-pro"
  "gemini-2.0-flash"
  "gemini-2.0-flash-lite"
)
SGPT_MODELS=(
  "gpt-4o"
  "gpt-4o-mini"
  "gpt-4-turbo"
  "o3-mini"
)

scan_providers() {
  local found=()
  for pid in "${!PROVIDER_ENV[@]}"; do
    local evar="${PROVIDER_ENV[$pid]}"
    local val="${!evar:-}"
    if [[ -n "$val" ]]; then
      found+=("$pid")
    fi
  done
  # Sort for consistent display
  IFS=$'\n' found=($(sort <<< "${found[*]}")); unset IFS
  printf '%s\n' "${found[@]}"
}

askall_load_config() {
  # Returns current config values (or defaults)
  local cfg_tools="" cfg_claude_model="" cfg_gemini_model="" cfg_sgpt_model="" cfg_max=""
  if [[ -f "$ASKALL_CONFIG" ]]; then
    while IFS='=' read -r k v; do
      [[ "$k" =~ ^[[:space:]]*# ]] && continue
      k="${k// /}"; v="${v// /}"
      case "$k" in
        ASKALL_TOOLS) cfg_tools="$v" ;;
        ASKALL_CLAUDE_MODEL) cfg_claude_model="$v" ;;
        ASKALL_GEMINI_MODEL) cfg_gemini_model="$v" ;;
        ASKALL_SGPT_MODEL) cfg_sgpt_model="$v" ;;
        ASKALL_MAX_TOOLS) cfg_max="$v" ;;
      esac
    done < "$ASKALL_CONFIG"
  fi
  echo "${cfg_tools:-auto}"
  echo "${cfg_claude_model:-(default)}"
  echo "${cfg_gemini_model:-gemini-2.5-flash}"
  echo "${cfg_sgpt_model:-(default)}"
  echo "${cfg_max:-0}"
}

askall_save_config() {
  local tools="$1" claude_m="$2" gemini_m="$3" sgpt_m="$4" max_t="$5"
  mkdir -p "$ASKALL_CONFIG_DIR"
  cat > "$ASKALL_CONFIG" <<CFGEOF
# askall configuration — generated by index.sh
# $(date -Iseconds)

# Which CLIs to use (comma-separated). "auto" or empty = detect all installed.
ASKALL_TOOLS=$tools

# Model overrides per CLI (empty = CLI default)
ASKALL_CLAUDE_MODEL=$claude_m
ASKALL_GEMINI_MODEL=$gemini_m
ASKALL_SGPT_MODEL=$sgpt_m

# Max simultaneous CLIs (0 = no limit)
ASKALL_MAX_TOOLS=$max_t
CFGEOF
  printf "${GREEN}✓ Config saved to %s${NC}\n" "$ASKALL_CONFIG"
}

pick_from_list() {
  local title="$1"; shift
  local options=("$@")
  local current="${options[0]}"

  echo ""
  printf "${BOLD}${CYAN}%s${NC}\n" "$title"
  echo "───────────────────────────────────────"
  for i in "${!options[@]}"; do
    printf "  ${BOLD}%d)${NC} %s\n" "$((i + 1))" "${options[$i]}"
  done
  printf "  ${BOLD}c)${NC} ${DIM}Custom input${NC}\n"
  printf "  ${BOLD}k)${NC} ${DIM}Keep current${NC}\n"
  echo ""
  read -rp "$(printf "${BOLD}Select [1-${#options[@]}/c/k]: ${NC}")" choice

  case "$choice" in
    [kK]|"") echo "__KEEP__" ;;
    [cC])
      read -rp "$(printf "${BOLD}Enter model ID: ${NC}")" custom
      echo "$custom"
      ;;
    [1-9]|[1-9][0-9])
      local idx=$((choice - 1))
      if (( idx >= 0 && idx < ${#options[@]} )); then
        echo "${options[$idx]}"
      else
        echo "__KEEP__"
      fi
      ;;
    *) echo "__KEEP__" ;;
  esac
}

configure_askall() {
  clear 2>/dev/null || true
  printf "${BOLD}${CYAN}"
  cat <<'BANNER'
  ┌──────────────────────────────────┐
  │     askall — Configuration       │
  └──────────────────────────────────┘
BANNER
  printf "${NC}\n"

  # ── 1. Scan providers ──────────────────────────────
  printf "${BOLD}Scanning .env for API keys...${NC}\n"
  local providers
  providers="$(scan_providers)"
  if [[ -n "$providers" ]]; then
    printf "${GREEN}Found providers:${NC}\n"
    while IFS= read -r p; do
      printf "  ${GREEN}●${NC} %s ${DIM}(%s)${NC}\n" "$p" "${PROVIDER_ENV[$p]}"
    done <<< "$providers"
  else
    printf "${YELLOW}No API keys found in environment.${NC}\n"
  fi

  # ── 2. Show installed CLIs ─────────────────────────
  echo ""
  printf "${BOLD}Installed CLIs:${NC}\n"
  local installed_clis=()
  for cli in claude gemini sgpt; do
    if command -v "$cli" >/dev/null 2>&1; then
      printf "  ${GREEN}●${NC} %s\n" "$cli"
      installed_clis+=("$cli")
    else
      printf "  ${RED}○${NC} %s ${DIM}(not installed)${NC}\n" "$cli"
    fi
  done

  # ── 3. Load current config ────────────────────────
  local cfg
  cfg="$(askall_load_config)"
  local cur_tools cur_claude cur_gemini cur_sgpt cur_max
  cur_tools="$(sed -n '1p' <<< "$cfg")"
  cur_claude="$(sed -n '2p' <<< "$cfg")"
  cur_gemini="$(sed -n '3p' <<< "$cfg")"
  cur_sgpt="$(sed -n '4p' <<< "$cfg")"
  cur_max="$(sed -n '5p' <<< "$cfg")"

  echo ""
  printf "${BOLD}Current config:${NC}\n"
  printf "  Tools:        %s\n" "$cur_tools"
  printf "  Claude model: %s\n" "$cur_claude"
  printf "  Gemini model: %s\n" "$cur_gemini"
  printf "  Sgpt model:   %s\n" "$cur_sgpt"
  printf "  Max CLIs:     %s\n" "$([ "$cur_max" = "0" ] && echo "no limit" || echo "$cur_max")"

  # ── 4. Select CLIs ────────────────────────────────
  echo ""
  printf "${BOLD}${CYAN}Select CLIs to use${NC}\n"
  echo "───────────────────────────────────────"
  printf "  ${BOLD}1)${NC} All installed (%s)\n" "${installed_clis[*]}"
  printf "  ${BOLD}2)${NC} Claude + Gemini only\n"
  printf "  ${BOLD}3)${NC} Claude only\n"
  printf "  ${BOLD}4)${NC} Gemini only\n"
  printf "  ${BOLD}5)${NC} Sgpt only\n"
  printf "  ${BOLD}c)${NC} ${DIM}Custom (comma-separated)${NC}\n"
  printf "  ${BOLD}k)${NC} ${DIM}Keep current${NC}\n"
  echo ""
  read -rp "$(printf "${BOLD}Select [1-5/c/k]: ${NC}")" cli_choice

  local new_tools="$cur_tools"
  case "$cli_choice" in
    1) new_tools="auto" ;;
    2) new_tools="claude,gemini" ;;
    3) new_tools="claude" ;;
    4) new_tools="gemini" ;;
    5) new_tools="sgpt" ;;
    [cC])
      read -rp "$(printf "${BOLD}CLIs (comma-separated, e.g. claude,gemini): ${NC}")" custom_tools
      [[ -n "$custom_tools" ]] && new_tools="$custom_tools"
      ;;
  esac

  # ── 5. Claude model ───────────────────────────────
  local new_claude="$cur_claude"
  if [[ "$new_tools" == *claude* ]] || [[ "$new_tools" == "auto" ]]; then
    local picked
    picked="$(pick_from_list "Claude model" "${CLAUDE_MODELS[@]}")"
    [[ "$picked" != "__KEEP__" ]] && new_claude="$picked"
  fi

  # ── 6. Gemini model ───────────────────────────────
  local new_gemini="$cur_gemini"
  if [[ "$new_tools" == *gemini* ]] || [[ "$new_tools" == "auto" ]]; then
    local picked
    picked="$(pick_from_list "Gemini model" "${GEMINI_MODELS[@]}")"
    [[ "$picked" != "__KEEP__" ]] && new_gemini="$picked"
  fi

  # ── 7. Sgpt model ─────────────────────────────────
  local new_sgpt="$cur_sgpt"
  if [[ "$new_tools" == *sgpt* ]] || [[ "$new_tools" == "auto" ]]; then
    local picked
    picked="$(pick_from_list "Sgpt/OpenAI model" "${SGPT_MODELS[@]}")"
    [[ "$picked" != "__KEEP__" ]] && new_sgpt="$picked"
  fi

  # ── 8. Max tools ───────────────────────────────────
  echo ""
  printf "${BOLD}${CYAN}Max simultaneous CLIs${NC} ${DIM}(0 = no limit, current: %s)${NC}\n" \
    "$([ "$cur_max" = "0" ] && echo "no limit" || echo "$cur_max")"
  read -rp "$(printf "${BOLD}Enter number [0-9/k=keep]: ${NC}")" max_choice
  local new_max="$cur_max"
  case "$max_choice" in
    [0-9]) new_max="$max_choice" ;;
  esac

  # ── 9. Clean up defaults for saving ────────────────
  [[ "$new_tools" == "auto" ]] && new_tools=""
  [[ "$new_claude" == "(default)" ]] && new_claude=""
  [[ "$new_sgpt" == "(default)" ]] && new_sgpt=""

  # ── 10. Summary & save ────────────────────────────
  echo ""
  printf "${BOLD}Summary:${NC}\n"
  printf "  Tools:        %s\n" "${new_tools:-auto (all installed)}"
  printf "  Claude model: %s\n" "${new_claude:-(CLI default)}"
  printf "  Gemini model: %s\n" "${new_gemini}"
  printf "  Sgpt model:   %s\n" "${new_sgpt:-(CLI default)}"
  printf "  Max CLIs:     %s\n" "$([ "$new_max" = "0" ] && echo "no limit" || echo "$new_max")"
  echo ""
  read -rp "$(printf "${BOLD}Save? [Y/n]: ${NC}")" confirm
  case "$confirm" in
    [nN]) printf "${YELLOW}Cancelled.${NC}\n"; return 0 ;;
  esac

  askall_save_config "$new_tools" "$new_claude" "$new_gemini" "$new_sgpt" "$new_max"
}

# ── Script registry ──────────────────────────────────────
# Format: "filename|description|requires_interaction"
SCRIPTS=(
  "install.sh|Full shell environment setup (zsh, tools, config)|yes"
  "setup-shellgpt.sh|ShellGPT with multi-provider/model support|yes"
  "setup-micro-minimal.sh|Micro editor minimal configuration|no"
  "setup-termux-keys-layout.sh|Termux extra keyboard layout|no"
  "reset-zsh-history.sh|Seed zsh history with useful commands|no"
)

# ── Helpers ───────────────────────────────────────────────

draw_header() {
  clear 2>/dev/null || true
  printf "${BOLD}${CYAN}"
  cat <<'BANNER'
  ┌──────────────────────────────────┐
  │         shell-setup              │
  │      Setup Script Index          │
  └──────────────────────────────────┘
BANNER
  printf "${NC}\n"
}

draw_menu() {
  local selected="$1"
  local count="${#SCRIPTS[@]}"

  for i in "${!SCRIPTS[@]}"; do
    IFS='|' read -r filename desc interactive <<< "${SCRIPTS[$i]}"

    # Check if script exists
    local exists=true
    [[ ! -f "$SCRIPT_DIR/$filename" ]] && exists=false

    local prefix="  "
    local color="$NC"
    local marker=" "

    if [[ "$i" -eq "$selected" ]]; then
      prefix="${BOLD}${GREEN}▸ "
      color="${BOLD}${GREEN}"
      marker=""
    fi

    if ! $exists; then
      color="${DIM}"
      marker=" (missing)"
    fi

    printf "${prefix}${color}%d) %-35s${DIM} %s${NC}%s\n" \
      "$((i + 1))" "$filename" "$desc" "$marker"
  done

  echo ""
  printf "  ${BOLD}${YELLOW}c) Configure askall${NC}\n"
  printf "  ${DIM}a) Run all (non-interactive only)${NC}\n"
  printf "  ${DIM}q) Quit${NC}\n"
  echo ""
}

run_script() {
  local idx="$1"
  IFS='|' read -r filename desc interactive <<< "${SCRIPTS[$idx]}"

  local script_path="$SCRIPT_DIR/$filename"

  if [[ ! -f "$script_path" ]]; then
    printf "${RED}Script not found: %s${NC}\n" "$script_path"
    return 1
  fi

  if [[ ! -x "$script_path" ]]; then
    chmod +x "$script_path"
  fi

  echo ""
  printf "${BOLD}${CYAN}── Running: %s ──${NC}\n\n" "$filename"
  bash "$script_path" "${@:2}"
  local rc=$?
  echo ""

  if [[ $rc -eq 0 ]]; then
    printf "${GREEN}✓ %s completed successfully${NC}\n" "$filename"
  else
    printf "${RED}✗ %s exited with code %d${NC}\n" "$filename" "$rc"
  fi

  return $rc
}

run_all_noninteractive() {
  printf "${BOLD}${CYAN}Running all non-interactive scripts...${NC}\n\n"

  local failed=0
  for i in "${!SCRIPTS[@]}"; do
    IFS='|' read -r filename desc interactive <<< "${SCRIPTS[$i]}"

    if [[ "$interactive" == "no" ]] && [[ -f "$SCRIPT_DIR/$filename" ]]; then
      run_script "$i" || ((failed++))
      echo ""
    fi
  done

  if [[ $failed -eq 0 ]]; then
    printf "${GREEN}All scripts completed successfully${NC}\n"
  else
    printf "${YELLOW}%d script(s) had errors${NC}\n" "$failed"
  fi
}

# ── FZF mode (if available) ──────────────────────────────

run_fzf_mode() {
  local entries=""
  # Add configure askall as first entry
  entries+="$(printf "⚙  %-35s  %s" "configure-askall" "Configure askall CLIs, models, providers")\n"
  for i in "${!SCRIPTS[@]}"; do
    IFS='|' read -r filename desc interactive <<< "${SCRIPTS[$i]}"
    local status="✓"
    [[ ! -f "$SCRIPT_DIR/$filename" ]] && status="✗"
    entries+="$(printf "%s  %-35s  %s" "$status" "$filename" "$desc")\n"
  done

  local choice
  choice="$(printf "$entries" | fzf \
    --header="shell-setup: Select script or configure" \
    --reverse \
    --height=50% \
    --border=rounded \
    --prompt="▸ " \
    --no-multi 2>/dev/null)" || return 0

  # Extract filename from selection
  local selected_file
  selected_file="$(echo "$choice" | awk '{print $2}')"

  # Handle configure-askall
  if [[ "$selected_file" == "configure-askall" ]]; then
    configure_askall
    return $?
  fi

  # Find matching script index
  for i in "${!SCRIPTS[@]}"; do
    IFS='|' read -r filename _ _ <<< "${SCRIPTS[$i]}"
    if [[ "$filename" == "$selected_file" ]]; then
      run_script "$i"
      return $?
    fi
  done
}

# ── Simple menu mode ─────────────────────────────────────

run_simple_menu() {
  while true; do
    draw_header
    draw_menu -1
    read -rp "$(printf "${BOLD}Select [1-${#SCRIPTS[@]}/a/q]: ${NC}")" choice

    case "$choice" in
      q|Q|quit|exit)
        echo "Bye!"
        exit 0
        ;;
      c|C)
        configure_askall
        echo ""
        read -rp "Press Enter to continue..."
        ;;
      a|A|all)
        run_all_noninteractive
        echo ""
        read -rp "Press Enter to continue..."
        ;;
      [1-9]|[1-9][0-9])
        local idx=$((choice - 1))
        if (( idx >= 0 && idx < ${#SCRIPTS[@]} )); then
          run_script "$idx"
          echo ""
          read -rp "Press Enter to continue..."
        else
          printf "${RED}Invalid choice${NC}\n"
          sleep 1
        fi
        ;;
      *)
        printf "${RED}Invalid choice${NC}\n"
        sleep 1
        ;;
    esac
  done
}

# ── CLI mode (direct execution) ──────────────────────────

usage() {
  cat <<EOF
index.sh - Shell-setup script launcher

Usage: ./index.sh [OPTIONS]

Options:
  (no args)              Interactive menu (fzf if available, otherwise numbered)
  --list                 List available scripts
  --run SCRIPT           Run a specific script by name
  --run-all              Run all non-interactive scripts
  --configure-askall     Configure askall CLIs, models, providers
  --fzf                  Force fzf mode
  --simple               Force simple numbered menu
  -h, --help             Show this help

Examples:
  ./index.sh                              # Interactive menu
  ./index.sh --configure-askall           # Configure askall
  ./index.sh --run setup-shellgpt.sh      # Run specific script
  ./index.sh --run install.sh --all       # Pass flags to script
  ./index.sh --run-all                    # All non-interactive scripts
EOF
}

# ── Main ──────────────────────────────────────────────────

main() {
  case "${1:-}" in
    -h|--help)
      usage
      exit 0
      ;;
    --list)
      printf "${BOLD}Available scripts:${NC}\n\n"
      for i in "${!SCRIPTS[@]}"; do
        IFS='|' read -r filename desc interactive <<< "${SCRIPTS[$i]}"
        local status="${GREEN}✓${NC}"
        [[ ! -f "$SCRIPT_DIR/$filename" ]] && status="${RED}✗${NC}"
        printf "  %b %-35s %s\n" "$status" "$filename" "$desc"
      done
      ;;
    --run)
      shift
      local target="${1:?Script name required}"
      shift
      for i in "${!SCRIPTS[@]}"; do
        IFS='|' read -r filename _ _ <<< "${SCRIPTS[$i]}"
        if [[ "$filename" == "$target" ]]; then
          run_script "$i" "$@"
          exit $?
        fi
      done
      err "Script not found: $target"
      exit 1
      ;;
    --run-all)
      run_all_noninteractive
      ;;
    --configure-askall)
      configure_askall
      ;;
    --fzf)
      run_fzf_mode
      ;;
    --simple)
      run_simple_menu
      ;;
    "")
      # Auto-select: fzf if available, otherwise simple menu
      if command -v fzf >/dev/null 2>&1; then
        run_fzf_mode
      else
        run_simple_menu
      fi
      ;;
    *)
      err "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
}

main "$@"
